# Generated by Django 3.1.1 on 2020-10-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_arrival_channel', models.CharField(blank=True, choices=[('Вебсайт', 'Вебсайт'), ('Контекстная реклама', 'Контекстная реклама'), ('Социальные сети', 'Социальные сети'), ('СМС-таргетинг', 'СМС-таргетинг'), ('Наружная реклама', 'Наружная реклама'), (' Радио', 'Радио'), ('ТВ', 'ТВ')], default='Вебсайт', max_length=50, verbose_name='Канал прихода клиента')),
                ('purchase_sales', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка клиента в %')),
                ('purchase_detail', models.CharField(blank=True, max_length=50, verbose_name='Сумма покупки/общее кол-во покупок клиента')),
                ('purchase_detail_type', models.CharField(blank=True, choices=[('Наличные', 'Наличные'), ('Безналичный', 'Безналичный'), ('Через сайт', 'Через сайт'), ('Кредит', 'Кредит'), ('Рассрочка', 'Рассрочка'), ('Другой способ', (('Пайпал', 'Пайпал'), ('Яндекс касса', 'Яндекс касса'), ('Социальные сети', 'Социальные сети')))], default='Наличные', max_length=50, verbose_name='Как платит')),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон клиента')),
                ('customer_post', models.EmailField(blank=True, max_length=254, verbose_name='Почта клиента')),
                ('customer_vkontakt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ссылка на профиль в VK')),
                ('customer_odnoklassnik', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ссылка на профиль в Однокласниках')),
                ('customer_instagram', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ссылка на профиль в Instagram')),
                ('customer_tiktok', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ссылка на профиль в Тикток')),
                ('customer_fb', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ссылка на профиль в Фейсбук')),
                ('customer_whatsap', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон для вотсап')),
                ('customer_fio', models.CharField(blank=True, max_length=20, null=True, verbose_name='ФИО')),
                ('customer_address', models.CharField(blank=True, max_length=80, null=True, verbose_name='Адрес')),
                ('customer_birthday', models.CharField(blank=True, max_length=20, null=True, verbose_name='День рождения 03/03/03')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
    ]
