# Generated by Django 3.1.1 on 2020-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addform', '0002_auto_20201003_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_smms',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Социальные сети клиента'),
        ),
    ]
