# Generated by Django 3.1.1 on 2020-10-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addform', '0003_customers_customer_smms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_smms',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Социальные сети клиента'),
        ),
    ]
