# Generated by Django 3.1.1 on 2020-10-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addform', '0004_auto_20201006_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_smms',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Социальные сети клиента'),
        ),
    ]
