# Generated by Django 3.1.1 on 2020-10-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addform', '0005_auto_20201006_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_post',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта клиента'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_smms',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Социальные сети клиента'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='purchase_detail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сумма/кол-во'),
        ),
    ]
